#!/usr/bin/env zsh
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
	if [[ "$filename" = _* ]]; then
		echo "stow --adopt $folder"
		stow --adopt $folder
	else
		echo "stow $folder"
		stow --restow $folder
	fi
done
popd
