#!/usr/bin/env zsh

STOW_FOLDERS="tmux,zsh,bin,sway,i3,waybar"
pushd ~/dotfiles
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd
