#!/usr/bin/env zsh

local flag_clean=false
local flag_install=false
opterr() { echo >&2 "install dotfiles: Unknown option '$1'" }
while (( $# )); do
	case $1 in
		--)                 shift; positional+=("${@[@]}"); break  ;;
		-c|--clean)         flag_clean=true                        ;;
		-i|--install)       flag_install=true                      ;;
		-*)                 opterr $1 && return 2                  ;;
		*)                  positional+=("${@[@]}"); break         ;;
	esac
	shift
done

STOW_FOLDERS="tmux,nvim,_zsh,bin,sway,i3,waybar,fuzzel,wlogout,wezterm,alacritty,golangciSettings"

DOTFILES=$HOME/dotfiles

if $flag_clean
then
	STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/cleanenv
else
	flag_install=true
fi

if $flag_install
then
	STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
fi
